name: Allure Docker Service GHCR Workflow

on:
  push:
    branches: [ "dev", "master" ]
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  ALLURE_RELEASE: 2.27.0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Determine Dockerfile to use
      id: select_dockerfile
      run: |
        echo "dockerfile=Dockerfile.bionic-simple" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
          docker build -t ghcr.io/${{ github.repository_owner }}/allure-docker-service:dev \
            --build-arg ARCH=amd64 \
            --build-arg JDK=adoptopenjdk:11-jre-openj9-bionic \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILD_VERSION=dev \
            --build-arg BUILD_REF=${GITHUB_SHA::8} \
            --build-arg ALLURE_RELEASE=${ALLURE_RELEASE} \
            -f ./docker/${{ steps.select_dockerfile.outputs.dockerfile }} .
          docker push ghcr.io/${{ github.repository_owner }}/allure-docker-service:dev
        elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
          docker build -t ghcr.io/${{ github.repository_owner }}/allure-docker-service:main \
            --build-arg ARCH=amd64 \
            --build-arg JDK=adoptopenjdk:11-jre-openj9-bionic \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILD_VERSION=main \
            --build-arg BUILD_REF=${GITHUB_SHA::8} \
            --build-arg ALLURE_RELEASE=${ALLURE_RELEASE} \
            -f ./docker/${{ steps.select_dockerfile.outputs.dockerfile }} .
          docker push ghcr.io/${{ github.repository_owner }}/allure-docker-service:main
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          docker build -t ghcr.io/${{ github.repository_owner }}/allure-docker-service:${VERSION} \
            -t ghcr.io/${{ github.repository_owner }}/allure-docker-service:latest \
            --build-arg ARCH=amd64 \
            --build-arg JDK=adoptopenjdk:11-jre-openj9-bionic \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILD_VERSION=${VERSION} \
            --build-arg BUILD_REF=${GITHUB_SHA::8} \
            --build-arg ALLURE_RELEASE=${ALLURE_RELEASE} \
            -f ./docker/${{ steps.select_dockerfile.outputs.dockerfile }} .
          docker push ghcr.io/${{ github.repository_owner }}/allure-docker-service:${VERSION}
          docker push ghcr.io/${{ github.repository_owner }}/allure-docker-service:latest
        fi

    - name: Remove the local images
      run: |
        docker rmi ghcr.io/${{ github.repository_owner }}/allure-docker-service:* || true
